<?php
namespace Ycn\Qiniu;

use yii\widgets\InputWidget;

/**
 * Created by PhpStorm.
 *
 * @author huangxianan <xianan_huang@163.com>
 * Date: 2018/4/26
 */

class UploadWidget extends InputWidget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        UploadWidget::register($this->view);
        return $this->renderInputHtml('file');
    }
}