<?php
namespace Ycn\Qiniu;

use Ycn\Qiniu\Assets\UploadAsset;
use yii\widgets\InputWidget;
use yii\helpers\Html;

/**
 * Created by PhpStorm.
 *
 * @author huangxianan <xianan_huang@163.com>
 * Date: 2018/4/26
 */

class UploadWidget extends InputWidget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        UploadAsset::register($this->view);
        return $this->renderInputHtml('file');
    }

    /**
     * @param string $type
     * @return string
     */
    public function renderInputHtml($type){

        $options = ['id'=>'file','onchange'=>'c()'];
        $this->options = array_merge($this->options,$options);

        if ($this->hasModel()) {
            $html = Html::activeInput($type, $this->model, $this->attribute, $this->options);
            $html .= Html::img("",['id' => 'show', 'width'=>200]);
            return $html;
        }
        return Html::input($type, $this->name, $this->value, $this->options);
    }
}